# Etapa de desarrollo del frontend
FROM node:18 AS development

WORKDIR /app

# Copia el package.json y el package-lock.json del frontend
COPY astro/package*.json ./

# Instala las dependencias del frontend
RUN npm install

# Copia el resto del código fuente del frontend
COPY astro/ .

# Exponemos el puerto 3000 para el frontend
EXPOSE 3000

# Comando para iniciar el servidor de desarrollo de Astro
CMD ["npm", "run", "dev"]
